#.travis.yml

language: node_js
node_js:
  - "8.0"

cache:
  directories:
    - $HOME/.npm

branches:
  only:
    - master

install:
  - npm i --silent --no-optional -g angular-cli-ghpages

script:
  - ng build --prod --output-path dist
  - ngh --repo="$GITHUB_ORG/$NAME.git" --name="$GITHUB_NAME" --email="$GITHUB_EMAIL"
