#.travis.yml

sudo: required
dist: trusty
language: node_js
node_js:
  - "8.0"

addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable

cache:
  directories:
    - $HOME/.npm
    - node_modules

env:
  global:
    - NAME="moose-watch"
    - GITHUB_ORG="https://$GH_TOKEN@github.com/bakesaled"
    - GITHUB_NAME="Brandon Eleuterio"
    - GITHUB_EMAIL="brandoneleuterio@hotmail.com"

before_install:
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  # Install cli
  - npm i --silent --no-optional -g @angular/cli
  - npm i --silent --no-optional -g angular-cli-ghpages

install:
  - npm i --silent --no-optional

script:
  - npm run test:ci
  - npm run build:ci

after_success:
  - test $TRAVIS_BRANCH = "master" && test $TRAVIS_PULL_REQUEST = "false" && ngh --repo=https://$GH_TOKEN@github.com/bakesaled/moose-watch.git --name="$GITHUB_NAME" --email="$GITHUB_EMAIL"
  - npm run coveralls
