#.travis.yml

language: node_js
node_js:
  - "8.0"

cache:
  directories:
    - $HOME/.npm

branches:
  only:
    - master

script:
  - ng build --prod --output-path dist

after_success:
  - npm run deploy
